# .github/workflows/release.yml
name: Release to PyPI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  ci:                      # <-- root job (no needs)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        with: { enable-cache: true }
      - run: rye sync
      - run: rye lint
      - run: rye test

  publish:
    needs: ci
    runs-on: ubuntu-latest

    # 1️⃣  Run in the same named environment you entered on PyPI
    environment:
      name: pypi                 # must match the “Environment name” field on PyPI

    # 2️⃣  Give this job the right to request an OIDC token
    permissions:
      contents: read             # keep least-privilege defaults
      id-token: write            # ★ mandatory for trusted publishing

    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        with: { enable-cache: true }

      # build + Twine check
      - run: |
          rye sync
          rye build --clean
          rye run twine check dist/*             # Twine comes from Rye venv

      # 3️⃣  Call the publish action **without** password/username
      - name: Publish to PyPI/TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: ${{ steps.repo.outputs.index_url }}   # keep if you need Test-PyPI for -rc tags
          skip-existing: true
