# .github/workflows/release.yml
name: Release to PyPI
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  ci:                      # <-- root job (no needs)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eifinger/setup-rye@v4
        with: { enable-cache: true }
      - run: rye sync
      - run: rye lint
      - run: rye test

  publish:
    needs: ci             # <-- now points to a job in the same file
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: eifinger/setup-rye@v4
        with: { enable-cache: true }

      - run: |
          rye sync
          rye build --clean
          rye run twine check dist/*             # Twine comes from Rye venv

      - id: repo
        run: |
          if [[ "${GITHUB_REF_NAME}" == *"-"* ]]; then
            echo "index_url=https://test.pypi.org/legacy/" >>"$GITHUB_OUTPUT"
          else
            echo "index_url=https://upload.pypi.org/legacy/" >>"$GITHUB_OUTPUT"
          fi

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository-url: ${{ steps.repo.outputs.index_url }}
          skip-existing: true
